FROM mariadb:10.4.18

ENV TZ Asia/Seoul
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=deverse
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD deverse.sql /docker-entrypoint-initdb.d/deverse.sql
ADD db_user.sql /docker-entrypoint-initdb.d/db_user.sql

WORKDIR /home/dev

EXPOSE 3306 33060