apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      tier: frontend
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
      name: tomcat
    spec:
      hostname: tomcat
      hostAliases:
      - ip: "10.100.59.9"
        hostnames:
        - "mariadb"
      containers:
      - name: tomcat
        image: bchwang/tomcat_mariadb:tomcat
        ports:
        - containerPort: 80
          name: tomcat
